version: "3.8"
services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    container_name: postgres
    ports:
      - ${DB_PORT}:5432
    volumes:
      - kcPostgres:/var/lib/postgresql/data
    networks:
     - keycloak-networks

  keycloak:
    build: .
    restart: unless-stopped
    container_name: keycloak
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:${DB_PORT}/${DB_NAME}
      - KC_DB_USERNAME=${DB_USERNAME}
      - KC_DB_PASSWORD=${DB_PASSWORD}

      - KC_HOSTNAME=${KC_HOSTNAME}
      - KC_HTTPS_KEY_STORE_PASSWORD=${KC_KEYSTORE_PASSWORD}

      - KEYCLOAK_ADMIN=${KC_ADMIN_USERNAME}
      - KEYCLOAK_ADMIN_PASSWORD=${KC_ADMIN_PASSWORD}
    ports:
      - ${KEYCLOAK_PORT}:8443
    networks:
     - keycloak-networks

volumes:
  kcPostgres:
networks:
    keycloak-networks:
