apiVersion: v1
kind: Service
metadata:
  name: keycloak-svc
  labels:
    app: keycloak-svc
spec:
  type: ClusterIP
  ports:
  - port: 3000
    protocol: TCP
  selector:
    app: keycloak
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak-service-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: keycloak.paymax.ng
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: keycloak-svc
            port:
              number: 3000




---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  selector:
    matchLabels:
      app: keycloak
  replicas: 1
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: frontend
        image: registry.digitalocean.com/bills-service/keycloak-service
        ports:
        - containerPort: 3000
