name: Deploy to DOKS

on:
  push:
    branches:
      - master
  pull_request:
    branches:
        - master


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          version: latest

      - name: Configure kubectl
        run: |
          doctl kubernetes cluster kubeconfig save  ${{ secrets.CLUSTER_NAME }}

      - name: Build and push Docker images
        run: |
          # Use docker-compose to build and push your images
          docker-compose build
          docker-compose push
