name: Deploy to DOKS

on:
  push:
    branches:
      - master
  pull_request:
    branches:
        - master


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          version: latest

      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ secrets.CLUSTER_NAME }}
      - name: config map and secrets for kubeconfig
        run: kubectl create configmap keycloak-configmap --from-literal=keycloak.keystore="$(cat keycloak.keystore)" --from-literal=hmo-realm.json="$(cat hmo-realm.json)"

      - name: Deploy to DigitalOcean Kubernetes
        run: kubectl apply -f k8s/manifest.yml

      - name: Verify deployment
        run: kubectl rollout status deployment/keycloak
